import React,{useState} from "react";import{createRoot}from"react-dom/client";import{ArrowRight,CheckCircle2,Search,Target,MessageSquare,ExternalLink}from"lucide-react";import"./style.css";

const CAL="https://calendly.com/thomasolesch-copywriting/kostenloses-kennenlerngespraech-30-minuten";
const EMAIL="ThomasOlesch.Copywriting@web.de";
const INST="https://www.instagram.com/thomas.olesch.copywriter/";

function Legal({type}:{type:"impressum"|"datenschutz"}){return <main className="legal"><a href="/">← Zurück zum Röntgen</a><h1>{type==="impressum"?"Impressum":"Datenschutz"}</h1>{type==="impressum"?<><h2>Angaben gemäß § 5 DDG</h2><p>Thomas Olesch – Copywriting<br/>Thomas Olesch<br/>Freiberuflicher Texter & Copywriter<br/>Sorsumer Hauptstraße 64<br/>31139 Hildesheim<br/>Deutschland</p><h2>Kontakt</h2><p>E-Mail: <a href={"mailto:"+EMAIL}>{EMAIL}</a></p><h2>Verantwortlich für den Inhalt</h2><p>Thomas Olesch, Anschrift wie oben.</p></>:<><p>Diese Datenschutzerklärung informiert über die Verarbeitung personenbezogener Daten auf dieser Website.</p><h2>Verantwortlicher</h2><p>Thomas Olesch – Copywriting<br/>Sorsumer Hauptstraße 64, 31139 Hildesheim<br/>E-Mail: <a href={"mailto:"+EMAIL}>{EMAIL}</a></p><h2>Hosting</h2><p>Die Website wird über Vercel bereitgestellt. Beim Aufruf können technisch erforderliche Verbindungsdaten verarbeitet werden.</p><h2>Website-Röntgen</h2><p>Wenn du das Formular nutzt, werden die von dir eingegebenen Daten zur Bearbeitung deiner Anfrage verarbeitet. Die Übermittlung erfolgt derzeit über FormSubmit. Die Daten werden nur für die Bearbeitung deiner Anfrage genutzt.</p><h2>Externe Links</h2><p>Links zu Calendly und Instagram führen zu externen Anbietern. Dort gelten die Datenschutzbestimmungen des jeweiligen Anbieters.</p><h2>Deine Rechte</h2><p>Du kannst im Rahmen der gesetzlichen Voraussetzungen Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit verlangen sowie einer Verarbeitung widersprechen.</p><p className="note">Hinweis: Diese Seite ersetzt keine individuelle Rechtsberatung.</p></>}</main>}

const CTA=({children="Kostenlosen Website-Check anfordern"}:{children?:React.ReactNode})=><a className="btn" href="#analyse">{children}<ArrowRight size={18}/></a>;

function App(){
const path=location.pathname;if(path==="/impressum")return <Legal type="impressum"/>;if(path==="/datenschutz")return <Legal type="datenschutz"/>;
const[status,setStatus]=useState("");
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("send");const f=new FormData(e.currentTarget);f.append("_subject","Neue Webseite-Röntgen Anfrage");f.append("_template","table");f.append("_captcha","false");try{const r=await fetch("https://formsubmit.co/ajax/"+EMAIL,{method:"POST",body:f,headers:{Accept:"application/json"}});if(!r.ok)throw 0;setStatus("ok");e.currentTarget.reset()}catch{setStatus("err")}}
return <><header><a className="brand" href="#"><span className="monogram">TO</span> WEBSEITE-RÖNTGEN</a><a className="mini" href="#analyse">Kostenlose Analyse anfordern</a></header>
<main>
<section className="hero"><div><p className="eyebrow">WENN BESUCHER KOMMEN, ABER ANFRAGEN AUSBLEIBEN</p><h1>Deine Website kann gut aussehen und trotzdem jeden Tag <mark>Anfragen verlieren.</mark></h1><p className="lead">Ich prüfe, wo Besucher aussteigen, was sie nicht verstehen und warum Google deine Seite womöglich anders einordnet als deine Wunschkunden. Danach weißt du, welche drei Stellen du zuerst ändern solltest.</p><CTA/><p className="micro">Kostenlos. Persönlich geprüft. Drei priorisierte Hebel.</p></div><div className="heroVisual"><div className="portraitFallback">TO</div><div className="diagnosis"><span>RÖNTGEN / STARTSEITE</span><h3>Hier verlieren Websites oft Anfragen.</h3><p>Unklare Botschaft · fehlende Zielgruppenansprache · schwache Nutzerführung · ungenutzte Suchintention</p></div></div></section><section className="truststrip"><div><p className="eyebrow">AUSBILDUNG & COMMUNITY</p><h3>Fundierte Ausbildung. Praxis. Austausch mit Copywritern, die täglich verkaufen müssen.</h3></div><a href="https://www.freedom-writer.de/" target="_blank" rel="noreferrer"><strong>Freedom Writer Academy</strong><span>Ausbildung im Conversion Copywriting</span></a><a href="https://www.the-copy-club.com/" target="_blank" rel="noreferrer"><strong>The Copy Club</strong><span>Aktives Mitglied · Copywriting-Community</span></a></section>

<section className="section"><p className="eyebrow">DER EIGENTLICHE DRUCK</p><h2>Menschen besuchen deine Website. Aber zu wenige davon werden zu Anfragen.</h2><div className="grid3"><article><h3>Besucher sind da. Im Postfach bleibt es still.</h3><p>Du bekommst Besucher, doch im Postfach passiert zu wenig. Das Problem: Du siehst nicht, an welcher Stelle Interesse verloren geht.</p></article><article><h3>Du änderst Texte und Design, ohne die Ursache zu kennen.</h3><p>Du änderst Headline, Texte oder Design. Trotzdem bleibt die entscheidende Frage offen: Warum klicken Interessenten nicht auf den nächsten Schritt?</p></article><article><h3>Google und deine Wunschkunden lesen zwei verschiedene Seiten.</h3><p>Menschen suchen nach einer Lösung, landen auf deiner Seite und erkennen nicht schnell genug: Hier bin ich richtig. Genau dort geht Conversion verloren.</p></article></div></section>

<section className="section dark"><p className="eyebrow">DER RÖNTGEN-BLICK</p><h2>Ich zeige dir die Stellen, an denen deine Website gerade Potenzial liegen lässt.</h2><p className="intro">Du bekommst Klarheit darüber, welche Änderungen zuerst Sinn ergeben und was du selbst umsetzen kannst.</p><div className="grid3 diagnostic"><article><Target/><b>01</b><h3>Conversion & Nutzerführung</h3><p>Versteht ein neuer Besucher in wenigen Sekunden, für wen die Seite ist, welches Problem du löst und was als Nächstes passiert?</p></article><article><MessageSquare/><b>02</b><h3>Copy & Positionierung</h3><p>Spricht deine Seite über das, was deinen Kunden wirklich beschäftigt, oder hauptsächlich darüber, was du anbietest?</p></article><article><Search/><b>03</b><h3>SEO & Suchintention</h3><p>Passt der Einstieg zu der Suchanfrage, über die deine Wunschkunden dich finden sollen?</p></article></div></section>

<section className="section"><p className="eyebrow">SO LÄUFT ES AB</p><h2>In drei Schritten weißt du, wo es hakt.</h2><div className="steps"><article><b>01</b><h3>Website schicken</h3><p>Du trägst URL und E-Mail ein und gibst mir kurz Kontext.</p></article><article><b>02</b><h3>Ich prüfe die kritischen Stellen</h3><p>Einstieg, Nutzerführung, Copy, Positionierung und Suchintention.</p></article><article><b>03</b><h3>Du bekommst drei priorisierte Hebel</h3><p>Eine klare Reihenfolge: was zuerst geändert werden sollte und welcher Hebel danach folgt.</p></article></div></section>

<section className="section proof"><p className="eyebrow">FEEDBACK & EINBLICKE</p><h2>Feedback und ein konkreter Projekt-Einblick.</h2><div className="proofgrid"><blockquote>„Die Landingpage sieht nach einem produktiven Schub aus, wie Sie den Röntgen-Blick beschreiben und werblich überzeugend präsentieren.“<footer>Claudia Kirsch · Unternehmensberatung</footer></blockquote><article className="case lukas"><span>PROJEKT-EINBLICK</span><h3>Lukas Kazimierski</h3><p>Website, Positionierung und Copy im konkreten Projektkontext. Hier kannst du dir die Seite selbst ansehen.</p><a href="https://www.lukas-kazimierski.de" target="_blank" rel="noreferrer">Website ansehen <ExternalLink size={16}/></a></article></div></section>

<section className="section monetize"><p className="eyebrow">WAS NACH DEM RÖNTGEN PASSIERT</p><h2>Du bekommst zuerst Klarheit. Die Umsetzung entscheidest du danach.</h2><p>Der Webseite-Röntgen ist kostenlos. Du bekommst von mir die drei wichtigsten Hebel und eine Einschätzung, was du selbst ändern kannst. Wenn du bei der Umsetzung Unterstützung möchtest, kann ich anschließend kostenpflichtig übernehmen, zum Beispiel Positionierung und Copy, Website- und Landingpage-Texte, SEO-Optimierung oder E-Mail-Marketing. Ob und was davon Sinn ergibt, besprechen wir erst nach dem Befund.</p><CTA>Analyse sichern</CTA></section>

<section id="analyse" className="section formsec"><div><p className="eyebrow">WEBSEITE-RÖNTGEN</p><h2>Schick mir die Seite, bei der du gerade nicht weißt, warum zu wenig zurückkommt.</h2><p>Du gibst mir ein paar Minuten Kontext. Ich schaue mir die Seite persönlich an und schicke dir die wichtigsten Befunde per E-Mail.</p><p className="checks"><CheckCircle2/> Persönlich von Thomas geprüft<br/><CheckCircle2/> Drei klare, priorisierte Hebel<br/><CheckCircle2/> Keine automatische Standardauswertung</p></div><form onSubmit={submit}><label>Website *<input name="website" type="url" required placeholder="https://..."/></label><label>E-Mail *<input name="email" type="email" required/></label><label>Name<input name="name" autoComplete="name"/></label><label>Was soll deine Website vor allem erreichen? *<select name="ziel" required defaultValue=""><option value="" disabled>Bitte wählen</option><option>Mehr Anfragen</option><option>Mehr Termine</option><option>Mehr Verkäufe</option><option>Mehr Sichtbarkeit</option><option>Mehr Vertrauen</option></select></label><label>Wen möchtest du erreichen? *<textarea name="zielgruppe" required/></label><label>Wonach sollen deine Wunschkunden bei Google suchen?<input name="suchanfrage"/></label><label>Was nervt dich aktuell am meisten an deiner Website?<textarea name="problem"/></label><p className="privacy">Mit dem Absenden bestätigst du, dass ich deine Angaben zur Bearbeitung deiner Anfrage verwenden darf. Mehr unter <a href="/datenschutz">Datenschutz</a>.</p><button className="btn" disabled={status==="send"}>{status==="send"?"Wird gesendet…":"Kostenlosen Röntgen-Check anfordern"}<ArrowRight size={18}/></button>{status==="ok"&&<p className="success">Danke! Deine Anfrage ist angekommen. Ich melde mich per E-Mail.</p>}{status==="err"&&<p className="error">Das hat leider nicht geklappt. Bitte versuche es erneut oder schreib direkt per E-Mail.</p>}</form></section>

<section className="section call"><p className="eyebrow">LIEBER IM GESPRÄCH?</p><h2>Du willst es lieber direkt besprechen?</h2><p>Dann buch dir ein kostenloses 30-minütiges Kennenlerngespräch.</p><a className="btn ghost" href={CAL} target="_blank" rel="noreferrer">Kostenloses Erstgespräch <ArrowRight size={18}/></a></section>
</main><footer className="footer"><span>© 2026 Thomas Olesch – Copywriting</span><nav><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href={INST} target="_blank" rel="noreferrer">Instagram</a></nav></footer></>}
createRoot(document.getElementById("root")!).render(<App/>);